### ISSUE TITLE
Temp. mod installation not working

### ISSUE THREAD

**Issue by just-a-beginner** [Meliox/PVE-mods#10]
The installation of the temp. mod is not working for me on a Proxmox 8 node:

```
root@pve:~# sh pve-mod-gui-temp.sh install
pve-mod-gui-temp.sh: 15: Syntax error: "(" unexpected
```

Anybody else who can reproduce it?

**Comment by Sh4Dz** [comment]
Hello,

I'm not sure if it's the correct method, but I used these commands :
chmod +x pve-mod-gui-temp.sh
./pve-mod-gui-temp.sh install

**Comment by just-a-beginner** [comment]
Thanks, that did the job.

**Comment by Meliox** [comment]
It's a bash she'll script, not a sh shell script. Hence should be executed with "bash..." to avoid syntax errors etc. ". /" allso works as the correct shell is read from the script.
