### ISSUE TITLE
system without lm-sensors installed sits on a loading screen 

### ISSUE THREAD

**Issue by MasterCATZ** [Meliox/PVE-mods#17]
if I log into a Proxmox GUI with any server that had lm-sensors installed temperatures will show ,

but for systems that do not have lm-sensors installed the entire page becomes frozen 

any way to put a check in place so it will skip trying to load data that does not exist ? 

![Screenshot from 2023-11-04 20-47-07](https://github.com/Meliox/PVE-mods/assets/1857824/2311cb30-b6cc-428f-a3e7-bab048bac4d9)
![Screenshot from 2023-11-04 20-47-17](https://github.com/Meliox/PVE-mods/assets/1857824/56b3885a-1e1f-4358-a943-ead1ccd899e1)
![Screenshot from 2023-11-04 20-47-27](https://github.com/Meliox/PVE-mods/assets/1857824/cd305674-7ffb-4e81-98c4-54bf7329d4f6)

if I log into proxmox GUI on that machine instead of using the data center list 
![Screenshot from 2023-11-04 20-48-28](https://github.com/Meliox/PVE-mods/assets/1857824/ef0e8c04-566a-4367-9967-83228d9b4371)

**Comment by Meliox** [comment]
Hi,

There may be other issues as well, as a node setup was not considered. The easiest approach may be to install lm-sensors.

Anyhow, as I don't have such a setup available, I need you test test the approach to understand where it stops

In /usr/share/perl5/PVE/API2/Nodes.pm

Find the line:  $res->{thermalstate} = `sensors -j`;

replace `sensors -j` with ""

Refresh your browser - does the freezing still happen - all information should be empty.

**Comment by eremem** [comment]
@Meliox I added an additional check for missing `sensors` output which should also fix the loading problem reported here.

**Comment by Meliox** [comment]
Closing this as reported fixed. Feel free to reopen if it still is a problem.

**Comment by Meliox** [comment]
Closing this as reported fixed. Feel free to reopen if it still is a problem.
