### ISSUE TITLE
sensors not showing under reverse proxy

### ISSUE THREAD

**Issue by andrei4002** [Meliox/PVE-mods#20]
got a weird issue with showing up the temp sensors when under a reverse proxy

so going to local-network-ip:8006 shows the sensors, but when opening the page using a domain, setup under traefik w/ssl, they don't show up at all, like it's the original page loading without any mods

i don't think it's a browser cache issue since i tried in multiple browsers and all have the same behavior

this is under rev proxy:
![image](https://github.com/Meliox/PVE-mods/assets/475334/f1e14f25-5d3e-4df3-91d3-8ef660f82177)

this is under local ip access:
![image](https://github.com/Meliox/PVE-mods/assets/475334/47f9aca2-4d0a-4724-9873-686bb6c6f4d3)

can't say if it's really an issue with the mod (it doesn't sound like it) but wanted to report it, maybe there's an idea to fix it

**Comment by Meliox** [comment]
Hello,
Yes, that's weird. I am not seeing the same as you. It's working well under traefik w. ssl.
![Skærmbillede 2024-03-31 160133](https://github.com/Meliox/PVE-mods/assets/5264368/9e85bf25-308b-43b4-ba2a-d776504d4e48)

**Comment by andrei4002** [comment]
2 days later, they magically started showing up as well. no clue what happened though
