### ISSUE TITLE
Proxmox 8?

### ISSUE THREAD

**Issue by sampl3x** [Meliox/PVE-mods#3]
Does this script work on the new Proxmox version 8?

**Comment by sampl3x** [comment]
Thank you for the update, it works!

Possible to make an option to not show HDD/SSD Thermal State when there is not HDD/SSD used? I have only nvme and give me a HDD/SSD Thermal State in de Summary.

**Comment by Meliox** [comment]
Hi,
Please try the above referred version.

**Comment by sampl3x** [comment]
Sorry,I don't know how to get that version.

**Comment by Meliox** [comment]
https://raw.githubusercontent.com/Meliox/PVE-mods/d63e83c62979aa3c22035f39359066a62df376f3/pve-mod-gui-temp.sh

**Comment by sampl3x** [comment]
Thank you, i tested it and it only show the NVME but i dont know what to fill in on the questions, now no cpu info is not shown.
Enter the cpu adapter name: ???
Enter the cpu item prefix: ???

**Comment by Meliox** [comment]
What is shown when you type sensors - j?

**Comment by Meliox** [comment]
Resolved in b642d4c
