### ISSUE TITLE
Add extra host info (hardware models / serials)

### ISSUE THREAD

**Issue by ITJamie** [Meliox/PVE-mods#45]
It would be great if extra hardware model info could be displayed.

manufacturer
model
serial

these can be parsed out of demidecode pretty easily

```
dmidecode -t 1
# dmidecode 3.4
Getting SMBIOS data from sysfs.
SMBIOS 2.8 present.

Handle 0x0100, DMI type 1, 27 bytes
System Information
        Manufacturer: Dell Inc.
        Product Name: PowerEdge R630
        Version: Not Specified
        Serial Number: FAKESERIAL
        UUID: FAKEUUID
        Wake-up Type: Power Switch
        SKU Number: SKU=NotProvided;ModelName=PowerEdge R630
        Family: Not Specified
```

**Comment by Meliox** [comment]
May I ask why manufacturer and product is of interest for you?

**Comment by ITJamie** [comment]
We have a lot of different hardware providers. Some of the model numbers on asrock or supermicro boxes dont make it in anyway obvious at first glance what the server type is

**Comment by Meliox** [comment]
Ok, could you list what information would be needed?

Suggestion for where it could be? https://raw.githubusercontent.com/Meliox/PVE-mods/main/pve-mod-sensors.png

Also, is dmidecode a standard Linux tool available in proxmox? (don't have access right now)

**Comment by eremem** [comment]
@Meliox `dmidecode` seems to be available by default on a PVE installation.

**Comment by eremem** [comment]
@Meliox I guess the data provided by dmidecode in this use-case could be considered static, so the installer script, which is run with root privileges, could dump the output of dmidecode to a file in e.g. /usr/share/pve-manager/js/ and ideally also transform it to some more "digestible" format to avoid later conversions in runtime. The perl script could than just `cat` the dump file and make it available to the JS code via some new variable. How do you find such an approach?

**Comment by Meliox** [comment]
@eremem: That's a very good work around.  Yes, that can easily be done.

**Comment by Meliox** [comment]
![image](https://github.com/Meliox/PVE-mods/assets/5264368/efb4be96-560f-449b-a52f-ffbcbd70443d)

(nb. information not available on my system)

Maybe move to above Kernal Version?

**Comment by eremem** [comment]
@Meliox I'm getting the following error during the installation:
```
./pve-mod-gui-sensors.sh: line 260: syntax error near unexpected token `('
./pve-mod-gui-sensors.sh: line 260: `        title: gettext('System Information'),'
```

**Comment by Meliox** [comment]
@eremem yes... The PR is currently broken. I left the js code hanging until decision on where it should be placed.

**Comment by eremem** [comment]
> ![image](https://private-user-images.githubusercontent.com/5264368/336965746-efb4be96-560f-449b-a52f-ffbcbd70443d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MTc4MzEsIm5iZiI6MTcxNzYxNzUzMSwicGF0aCI6Ii81MjY0MzY4LzMzNjk2NTc0Ni1lZmI0YmU5Ni01NjBmLTQ0OWItYTUyZi1mZmJjYmQ3MDQ0M2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDVUMTk1ODUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2EyMDdlMTc5M2U4MGZiMzk4OWVkM2Q3OTFmMWI1MzkwMTQwYTg5YjVjNWM1MGRiN2UyNDQ5NzUyNGJmODYyMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Dd2PRs17arut9ZEGN3r_B6HYbsyRy6c-VXIBXGYtPVI)
> 
> (nb. information not available on my system)
> 
> Maybe move to above Kernal Version?
> 
> Let me know what you think @eremem, @ITJamie .

My first thought was about moving it before the kernel version so 👍 to that! 😄

**Comment by eremem** [comment]
Works and looks good:
![obraz](https://github.com/Meliox/PVE-mods/assets/56274896/8cfe28b2-f276-4063-8857-a71819713274)
