### ISSUE TITLE
No temp on AMD Embedded G-Series GX-420GI Radeon R7E

### ISSUE THREAD

**Issue by Undercore90** [Meliox/PVE-mods#48]
Hi,

Can you please help me to fix this error. It's probably a matter of correcting some file. Until the patch is released, I can edit it manually.

fam15h_power-pci-00c4
Adapter: PCI adapter
power1:       42.04 mW (avg =  67.69 mW, interval =   0.01 s)
                       (crit =  15.00 W)

amdgpu-pci-0008
Adapter: PCI adapter
vddgfx:      887.00 mV 
vddnb:       887.00 mV 
edge:         +48.0°C  

k10temp-pci-00c3
Adapter: PCI adapter
temp1:        +48.8°C  (high = +70.0°C)
                       (crit = +100.0°C, hyst = +99.0°C)

![image](https://github.com/Meliox/PVE-mods/assets/156170953/1fd6af82-1a36-45e0-b98c-c621305a9faa)

**Comment by Meliox** [comment]
Please provide the sensor -j output. Thanks.

**Comment by Undercore90** [comment]
Sure,

```
root@pve:~# sensors -j
{
   "fam15h_power-pci-00c4":{
      "Adapter": "PCI adapter",
      "power1":{
         "power1_average": 0.028,
         "power1_input": 0.033,
         "power1_crit": 15.000,
         "power1_average_interval": 0.010
      }
   },
   "amdgpu-pci-0008":{
      "Adapter": "PCI adapter",
      "vddgfx":{
         "in0_input": 0.887
      },
      "vddnb":{
         "in1_input": 0.887
      },
      "edge":{
         "temp1_input": 49.000
      }
   },
   "k10temp-pci-00c3":{
      "Adapter": "PCI adapter",
      "temp1":{
         "temp1_input": 49.250,
         "temp1_max": 70.000,
         "temp1_crit": 100.000,
         "temp1_crit_hyst": 99.000
      }
   }
}
```

**Comment by Undercore90** [comment]
Hi,

Any news here?

**Comment by Meliox** [comment]
Your AMD system is reporting temp differently. Can you try the version provided in #49 . Please uninstall first, then install the new one.

**Comment by Undercore90** [comment]
How to install #49 version?

**Comment by Undercore90** [comment]
![image](https://github.com/Meliox/PVE-mods/assets/156170953/cb7058fd-6b52-4181-a344-9d12ea58de01)
Ok something worked out I need to change the name again e.g. core and it will be fine.

**Comment by Undercore90** [comment]
Hi,

I did it this way:
cd /tmp
git clone https://github.com/Meliox/PVE-mods.git
cd PVE-mods
git fetch origin pull/49/head:pr-49
git checkout pr-49
bash pve-mod-gui-sensors.sh install

It didn't recognize my CPU it displayed sensors -j and asked where the CPU temperature was.

**Comment by Meliox** [comment]
Thanks for testing. Found the missing code line. Can I ask you to try again?
