### ISSUE TITLE
Install Instructions Not Working

### ISSUE THREAD

**Issue by rtorchia** [Meliox/PVE-mods#6]
I attempted to install this by by using the instructions given:
```
apt-get install lm-sensors
wget https://github.com/Meliox/PVE-mods/blob/main/pve-mod-gui-temp.sh
```
but this just returned an error from bash:
>pve-mod-gui-temp.sh: line 1: unexpected EOF while looking for matching `)'
>pve-mod-gui-temp.sh: line 2: syntax error: unexpected end of file

To correct this I did the following:

1. Deleted the download .sh file (rm pve-mod-gui-temp.sh)
2. Created new file (touch pve-mod-gui-temp.sh)
3. Opened this file (nano pve-mod-gui-temp.sh)
4. Copied the script from git's raw view of the code and pasted into nano
5. Saved the file and exited (CTRL-X)

I was then able to successfully execute the script with
```
pve-mod-gui-temp.sh install
````

Not sure if anyone else ever came across this, but maybe a change in the wget command to this may work better:
```
https://raw.githubusercontent.com/Meliox/PVE-mods/main/pve-mod-gui-temp.sh
```

**Comment by Meliox** [comment]
Thank you for letting me know. The urls has been corrected :)
