### ISSUE TITLE
Invalid entry length (0). DMI table is broken! Stop.

### ISSUE THREAD

**Issue by paf2332** [Meliox/PVE-mods#67]
When running the bash pve-mod-gui-sensors.sh install
I get an error 
Invalid entry length (0). DMI table is broken! Stop.
after the Sensors' output added to "/usr/share/perl5/PVE/API2/Nodes.pm".

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/Meliox/PVE-mods/assets/175206643/34f0c573-1a22-4bd0-a2a0-2477ade35f51)
**Sensors output**
If applicable, provide sensor datadump (use the argument save-sensors-data)

**Additional context**

**Comment by Meliox** [comment]
What is the result when executing?
```dmidecode -t 1```

**Comment by paf2332** [comment]
Hi 

 

Thanks for the reply

 

I’m running on an anonymous Chinese mini PC which looks as though it doesn’t return much information!

 



 

 

Paul Farrant

**Comment by Meliox** [comment]
Please share the output.

**Comment by paf2332** [comment]
dmidecode -t 1
# dmidecode 3.4
Getting SMBIOS data from sysfs.
SMBIOS 3.5.0 present.

Handle 0x0001, DMI type 1, 27 bytes
System Information
        Manufacturer: Default string
        Product Name: Default string
        Version: Default string
        Serial Number: Default string
        UUID: 03000200-0400-0500-0006-000700080009
        Wake-up Type: Power Switch
        SKU Number: Default string
        Family: Default string

Invalid entry length (0). DMI table is broken! Stop.

**Comment by Meliox** [comment]
Okay.. Well you have to ask your manufacturers to make a new bios with fixes for that.

You can disable system information with a no when asked during install. It does not bring any value to show anyhow.

**Comment by Meliox** [comment]
Closing this as it is an expected output by dmidecode in case of a broke table, hence it makes sense to keep it.
Workaround is to disable system information.

**Comment by Meliox** [comment]
Closing this as it is an expected output by dmidecode in case of a broke table, hence it makes sense to keep it.
Workaround is to disable system information.
